#!/usr/bin/env bash
# fixing port 80 nginx
# Remove default from enabled and creating new one in avialable
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart
service nginx restart
