#!/usr/bin/env bash
# Fixes a web server to run Nginx instead of root.
# setsearch user www and replace it by nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
 # kill apache2 and use nginix instead
pkill apache2
sudo -u nginx service nginx start
